### ISSUE TITLE
cannot fire a call using blink on getting started according to docs

### ISSUE THREAD

**Issue by Wrufesh** [davehorton/drachtio-server#108]
According to **[developer guide](https://www.drachtio.org/docs)** >> **Introduction** >> **Lets do something simple**

> Now fire up a sip client of some kind (e.g. Bria, Blink, or other), point it at the address your drachtio server is listening on, and place a call.

I needed to fire up a sip client.

I installed blink and tried to connect with a sip contact **sip:22@127.0.0.1** But blink fails to connect to it.

I have used drachtio/dractio-server:latest docker image.

And have assumed its default config has been used with contacts setting as
`<contact>sip:*;transport=udp,tcp</contact>` 

What am I missing here?

**Comment by davehorton** [comment]
can you change the port in the srf.connect(.. to 9022 instead of 9021 and try again?  I see that I have a typo on the web page.

You'll need to also start your docker container with host networking on.

When you try this if it doesn't seem to be working, please provide the output from the docker container as well as your node app

**Comment by Wrufesh** [comment]
No I am successfully able to connect drachtio-srf with drachtio-server. 

I am not able to reject a call as shown in example.

In order to reject a call I need to make a call using blink. 

In blink >> Add an existing sip account  >>  I used **sip:22@127.0.0.1** id without password.
Then I tried to fire a call. 
But it seems Blink is not able to connect to drachtio-server.

**Comment by davehorton** [comment]
Can you show the log file from the docker containerized drachtio server?  It should show an INVITE arriving; if not there is an issue with your Blink setup

**Comment by Wrufesh** [comment]
Hello again, I am here with the screenshots.

**drachtio-server (docker)**
![drachtio-server(docker)](https://user-images.githubusercontent.com/4590723/70452798-d6a65980-1acf-11ea-9029-8d9593549c90.png)


**drachtio-srf**
![drachtio-srf](https://user-images.githubusercontent.com/4590723/70452886-f473be80-1acf-11ea-905a-d529b580b878.png)


**port and process status**
![port-process-status](https://user-images.githubusercontent.com/4590723/70452915-0190ad80-1ad0-11ea-8f24-a95802a929cb.png)


**sip profile setting in twinkle**
![sip profile setting on twinkle/
](https://user-images.githubusercontent.com/4590723/70453061-3997f080-1ad0-11ea-89f4-db5e905d6d5a.png)

**twinkle error**
![twinkle error](https://user-images.githubusercontent.com/4590723/70453091-46b4df80-1ad0-11ea-924b-e87ac30cea47.png)

**Comment by davehorton** [comment]
well it seems to me the INVITEs are not reaching the drachtio server, so I think your problem may be with how you are running docker, or the softphone. 

Can you show the command you are using to run docker?

**Comment by Wrufesh** [comment]
It is as follow:

`docker run -p 9022:9022 -p 5060:5060 drachtio/drachtio-server:latest`

Do not I need only a sip contact to configure softphone?

**Comment by sloan58** [comment]
I'm struggling with this as well.  I initially tried the pre-packaged docker image and had the same results as mentioned above (9022 from app.js connects fine but SIP calls don't seem to arrive).  I then tried building the drachtio container myself but results are still the same.  In both scenarios I can telnet to 5060 successfully and when watching the dracthio output I can see the connection coming in ("tport_tcp_init")

I don't know if this is a SIP client issue or not, but a little more explanation on setting up this test call in the docs would be really helpful.  I make a lot of SIP calls but I don't usually make them to my localhost so I'm a little unsure if I'm doing this right.  One example with Bria, Blink or other would be awesome.

**Comment by davehorton** [comment]
the command above is only forward tcp traffic.  try
```
docker run -p 9022:9022 -p 127.0.0.1:5060:5060/udp drachtio/drachtio-server:latest
```

**Comment by sloan58** [comment]
Thanks for the quick response!

I modified the ports but still can't connect via SIP. 

`~ nc -vnzu 127.0.0.1 5060
Connection to 127.0.0.1 port 5060 [udp/*] succeeded!
~ nc -vnzt 127.0.0.1 5060
Connection to 127.0.0.1 port 5060 [tcp/*] succeeded!`

Here's my Linphone config (which given my network test successes could definitely be the problem...)

![image](https://user-images.githubusercontent.com/6303820/79458163-71073400-7fbf-11ea-8bb0-a4fd1266a274.png)

I'm placing the calls to `test@127.0.0.1`.  I don't see this traffic in Wireshark since it's not heading out the network interface so it's hard to see what's happening under the hood with Linphone.

Would you mind sharing what your soft client setup looks like for this test?

**Comment by oddsix** [comment]
You should be able to get a capture in Wireshark via the loopback(lo) interface.

> Thanks for the quick response!
> 
> I modified the ports but still can't connect via SIP.
> 
> `~ nc -vnzu 127.0.0.1 5060 Connection to 127.0.0.1 port 5060 [udp/*] succeeded!`
> 
> `~ nc -vnzt 127.0.0.1 5060 Connection to 127.0.0.1 port 5060 [tcp/*] succeeded!`
> 
> Here's my Linphone config (which given my network test successes could definitely be the problem...)
> 
> ![image](https://user-images.githubusercontent.com/6303820/79458163-71073400-7fbf-11ea-8bb0-a4fd1266a274.png)
> 
> I'm placing the calls to `test@127.0.0.1`. I don't see this traffic in Wireshark since it's not heading out the network interface so it's hard to see what's happening under the hood with Linphone.
> 
> Would you mind sharing what your soft client setup looks like for this test?

**Comment by sloan58** [comment]
> You should be able to get a capture in Wireshark via the loopback(lo) interface.

Thanks, great tip.  I had to scroll down in the Wireshark panel to see the loopback interface - didn't even know it was there!  I'll grab a pcap to see what's going on.

**Comment by davehorton** [comment]
I use Bria and my config looks like this

![image](https://user-images.githubusercontent.com/1884973/79460164-69955a00-7fc2-11ea-93fc-ac42b5e1feb4.png)

**Comment by sloan58** [comment]
Boom!  Bria FTW!

I'm not sure what the key factor is here.  I can now get a response using your settings and even removing the proxy address (which I thought was the key to getting this to work at first).  I'm capturing on my loopback and when I use Bria I can see the traffic but when I use Linphone I don't.

Thanks for the quick support to get this working.

**Comment by oddsix** [comment]
Just a quick follow up on linphone, I just tried it and immediately saw a problem.  If you are doing everything on localhost, then you are going to run into problems with ports.  The way I just solved it was to start the docker container on an alternate port, 5064 in my case.  You could also configure linphone to bind to a different port as well.  Ultimately, my docker run command was this:

docker run -p 9022:9022 -p 127.0.0.1:5064:5060/udp drachtio/drachtio-server:latest

I then configured my SIP account in Linphone to send calls to 5064 and all was well.

**Comment by Wrufesh** [comment]
I fixed it by handling a REGISTER request in drachtio-srf.
I noticed blink was sending REGISTER request and was throwing error asI had just copy pasted getting started code and it has no code for handling REGISTER request.

**Comment by sloan58** [comment]
> Just a quick follow up on linphone, I just tried it and immediately saw a problem. If you are doing everything on localhost, then you are going to run into problems with ports. The way I just solved it was to start the docker container on an alternate port, 5064 in my case. You could also configure linphone to bind to a different port as well. Ultimately, my docker run command was this:
> 
> docker run -p 9022:9022 -p 127.0.0.1:5064:5060/udp drachtio/drachtio-server:latest
> 
> I then configured my SIP account in Linphone to send calls to 5064 and all was well.

Yep, you are so right.  I just confirmed by switching the ports that Linphone uses and it works fine.

![image](https://user-images.githubusercontent.com/6303820/79462748-eece3e00-7fc5-11ea-8d39-32341d09c79a.png)

I made the mistake of just turning these off the last time (started getting impatient and toggling all the things).  The key is to either pick a different port in Linphone or in drachtio - great find!

**Comment by sloan58** [comment]
> I fixed it by handling a REGISTER request in drachtio-srf.
> I noticed blink was sending REGISTER request and was throwing error asI had just copy pasted getting started code and it has no code for handling REGISTER request.

I'm not sure if Blink has this settings, but in Bria and Linphone you can toggle whether the client will attempt to register with the server.

![image](https://user-images.githubusercontent.com/6303820/79463106-6603d200-7fc6-11ea-815b-a9a4fe74cacc.png)

![image](https://user-images.githubusercontent.com/6303820/79463160-7916a200-7fc6-11ea-9f18-b7466c5dce9c.png)

Check out the "register" toggles for these and see if Blink has one.

**Comment by Yogita98** [comment]
Hey @davehorton @sloan58 @oddsix 
I'm trying to make a call from LinPhone but nothing appears on the terminal running the drachtio-server.
I followed the instructions in this thread but the problem persists. I'm attaching my config below:
Docker logs:

![image](https://user-images.githubusercontent.com/37609519/115225782-1ea9a780-a12c-11eb-8144-c16b325d5581.png)

Contact created on LinPhone:

![image](https://user-images.githubusercontent.com/37609519/115225896-3d0fa300-a12c-11eb-8b08-49b50a705fd1.png)

I have a sip server running on port 5060 which shows that I placed a call but `drachtio-server` won't show anything.
The command that I'm using to run drachtio is as shown:
`docker run -p 9022:9022 -p 127.0.0.1:5061:5060/tcp drachtio/drachtio-server:latest`

What do you guys think could be the problem?

**Comment by davehorton** [comment]
seems like you are sending a call to 5060 localhost, but you have mapped the containers port 5060 to 5061 on localhost?

**Comment by Yogita98** [comment]
Yeah I'm mapping the container's port 5060 to 5061 on localhost because my linphone is listening on 5061

![image](https://user-images.githubusercontent.com/37609519/115228167-1010bf80-a12f-11eb-9d0c-536a9da5216d.png)

**Comment by davehorton** [comment]
I'm confused:
- "my linphone is listening on 5061"
- "I have a sip server running on port 5060 which shows that I placed a call"
- and drachtio server is mapped to port 5061 on the host

What am I missing -- taken altogether, that doesn't make sense
